### ISSUE TITLE
DeprecationWarning: pkg_resources is deprecated as an API

### ISSUE THREAD

**Issue by graingert-coef** [dhatim/python-license-check#114]
liccheck should migrate to `importlib.metadata.distributions()`

**Comment by eldrift** [comment]
I get this:

liccheck -s liccheck.ini -r requirements.txt >> lisensstatus.txt
Traceback (most recent call last):
  File "C:\Users\terje\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\terje\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\terje\AppData\Local\Programs\Python\Python310\Scripts\liccheck.exe\__main__.py", line 7, in <module>
  File "C:\Users\terje\AppData\Local\Programs\Python\Python310\lib\site-packages\liccheck\command_line.py", line 529, in main
    sys.exit(run(args))
  File "C:\Users\terje\AppData\Local\Programs\Python\Python310\lib\site-packages\liccheck\command_line.py", line 509, in run
    return process(
  File "C:\Users\terje\AppData\Local\Programs\Python\Python310\lib\site-packages\liccheck\command_line.py", line 317, in process
    pkg_info = get_packages_info(requirement_file, no_deps)
  File "C:\Users\terje\AppData\Local\Programs\Python\Python310\lib\site-packages\liccheck\command_line.py", line 195, in get_packages_info
    packages = [transform(dist) for dist in resolve_func(requirements)]
  File "C:\Users\terje\AppData\Local\Programs\Python\Python310\lib\site-packages\liccheck\command_line.py", line 195, in <listcomp>
    packages = [transform(dist) for dist in resolve_func(requirements)]
  File "C:\Users\terje\AppData\Local\Programs\Python\Python310\lib\site-packages\liccheck\requirements.py", line 51, in resolve
    for dist in pkg_resources.working_set.resolve(requirements):
  File "C:\Users\terje\AppData\Local\Programs\Python\Python310\lib\site-packages\pkg_resources\__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
**pkg_resources.ContextualVersionConflict: (websockets 12.0 (c:\users\terje\appdata\local\programs\python\python310\lib\site-packages), Requirement.parse('websockets<11,>=10; python_version > "3.6" and extra == "websockets"'), {'gql'})**


Python 3.10
Win 11
