### ISSUE TITLE
failed to parse output from uv

### ISSUE THREAD

**Issue by EMCP** [dhatim/python-license-check#123]
I utilize uv , a package manager akin to poetry.. which is based on toml files instead of requirements.txt 

but it does allow exporting of the uv.lock file to a requirements.txt file likeso

` uv export --no-hashes --format requirements-txt > requirements.txt`

however, when I attempted to use this with liccheck, it failed.. here is the requirements.txt and output

```
# This file was autogenerated by uv via the following command:
#    uv export --no-hashes --format requirements-txt --resolution highest
aiohappyeyeballs==2.4.3
aiohttp==3.10.10
aiosignal==1.3.1
alembic==1.13.3
altair==5.4.1
annotated-types==0.7.0
anyio==4.6.2.post1
arize-phoenix-evals==0.17.2
attrs==24.2.0
azure-common==1.1.28
azure-core==1.31.0
azure-data-tables==12.5.0
azure-identity==1.19.0
azure-search-documents==11.5.1
beautifulsoup4==4.12.3
blinker==1.8.2
cachetools==5.5.0
certifi==2024.8.30
cffi==1.17.1 ; platform_python_implementation != 'PyPy'
charset-normalizer==3.4.0
click==8.1.7
cloudpickle==3.1.0
colorama==0.4.6 ; platform_system == 'Windows'
contourpy==1.3.0
cryptography==43.0.3
cycler==0.12.1
dataclasses-json==0.6.7
deprecated==1.2.14
dirtyjson==1.0.8
distro==1.9.0
docker==7.1.0
entrypoints==0.4
et-xmlfile==1.1.0
fastapi==0.115.2
fasttext-wheel==0.9.2
filelock==3.16.1
flask==3.0.3
fonttools==4.54.1
frozenlist==1.4.1
fsspec==2024.10.0
gitdb==4.0.11
gitpython==3.1.43
google-api-core==2.21.0
google-auth==2.35.0
googleapis-common-protos==1.65.0
graphene==3.4
graphql-core==3.2.5
graphql-relay==3.2.0
greenlet==3.1.1
gunicorn==21.2.0 ; platform_system != 'Windows'
h11==0.14.0
httpcore==1.0.6
httpx==0.27.2
huggingface-hub==0.26.0
idna==3.10
importlib-metadata==7.2.1
isodate==0.7.2
itsdangerous==2.2.0
jinja2==3.1.4
jiter==0.6.1
joblib==1.4.2
jsonschema==4.23.0
jsonschema-specifications==2024.10.1
kiwisolver==1.4.7
langid==1.1.6
llama-cloud==0.1.4
llama-index==0.11.19
llama-index-agent-openai==0.3.4
llama-index-cli==0.3.1
llama-index-core==0.11.19
llama-index-embeddings-azure-openai==0.2.5
llama-index-embeddings-openai==0.2.5
llama-index-indices-managed-llama-cloud==0.4.0
llama-index-legacy==0.9.48.post3
llama-index-llms-azure-openai==0.2.2
llama-index-llms-openai==0.2.15
llama-index-multi-modal-llms-openai==0.2.2
llama-index-program-openai==0.2.0
llama-index-question-gen-openai==0.2.0
llama-index-readers-file==0.2.2
llama-index-readers-llama-parse==0.3.0
llama-index-vector-stores-azureaisearch==0.2.2
llama-parse==0.5.10
mako==1.3.5
markdown==3.7
markdown-it-py==3.0.0
markupsafe==3.0.2
marshmallow==3.23.0
matplotlib==3.9.2
mdurl==0.1.2
mlflow==2.11.4
msal==1.31.0
msal-extensions==1.2.0
multidict==6.1.0
mypy-extensions==1.0.0
narwhals==1.10.0
nest-asyncio==1.6.0
networkx==3.4.1
nltk==3.9.1
numpy==1.26.4
openai==1.52.0
opencensus==0.11.4
opencensus-context==0.1.3
opencensus-ext-azure==1.1.13
openpyxl==3.1.5
packaging==23.2
pandas==2.2.3
pillow==10.4.0
portalocker==2.10.1
propcache==0.2.0
proto-plus==1.24.0
protobuf==4.25.5
psutil==6.1.0
pyarrow==15.0.2
pyasn1==0.6.1
pyasn1-modules==0.4.1
pybind11==2.13.6
pycparser==2.22 ; platform_python_implementation != 'PyPy'
pydantic==2.9.2
pydantic-core==2.23.4
pydantic-settings==2.6.0
pydeck==0.9.1
pygments==2.18.0
pyjwt==2.9.0
pymupdf==1.24.0
pymupdfb==1.24.0
pyodbc==5.1.0
pyparsing==3.2.0
pypdf==4.1.0
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
pytz==2024.2
pywin32==308 ; sys_platform == 'win32' or platform_system == 'Windows'
pyyaml==6.0.2
querystring-parser==1.2.4
referencing==0.35.1
regex==2024.9.11
requests==2.32.3
rich==13.9.2
rpds-py==0.20.0
rsa==4.9
ruff==0.7.0
scikit-learn==1.5.2
scipy==1.14.1
setuptools==75.2.0
six==1.16.0
smmap==5.0.1
sniffio==1.3.1
soupsieve==2.6
sqlalchemy==2.0.36
sqlparse==0.5.1
starlette==0.40.0
streamlit==1.39.0
striprtf==0.0.26
tenacity==8.5.0
threadpoolctl==3.5.0
tiktoken==0.8.0
toml==0.10.2
tornado==6.4.1
tqdm==4.66.5
typing-extensions==4.12.2
typing-inspect==0.9.0
tzdata==2024.2
urllib3==2.2.3
waitress==3.0.0 ; platform_system == 'Windows'
watchdog==5.0.3 ; platform_system != 'Darwin'
werkzeug==3.0.4
wrapt==1.16.0
yarl==1.15.5
zipp==3.20.2

```

Here is the output

```
liccheck -R liccheck-testresults.txt --no-deps                    
gathering licenses...
Traceback (most recent call last):
  File " /bin/liccheck", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File " /lib/python3.12/site-packages/liccheck/command_line.py", line 529, in main
    sys.exit(run(args))
             ^^^^^^^^^
  File " /lib/python3.12/site-packages/liccheck/command_line.py", line 509, in run
    return process(
           ^^^^^^^^
  File " /lib/python3.12/site-packages/liccheck/command_line.py", line 317, in process
    pkg_info = get_packages_info(requirement_file, no_deps)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File " /lib/python3.12/site-packages/liccheck/command_line.py", line 195, in get_packages_info
    packages = [transform(dist) for dist in resolve_func(requirements)]
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File " /lib/python3.12/site-packages/liccheck/requirements.py", line 41, in resolve_without_deps
    dist = env.best_match(
           ^^^^^^^^^^^^^^^
  File " /lib/python3.12/site-packages/pkg_resources/__init__.py", line 1260, in best_match
    dist = working_set.find(req)
           ^^^^^^^^^^^^^^^^^^^^^
  File " /lib/python3.12/site-packages/pkg_resources/__init__.py", line 729, in find
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (arize-phoenix-evals 0.17.0 ( /lib/python3.12/site-packages), Requirement.parse('arize-phoenix-evals==0.17.2'))


```

**Comment by JSchoeck** [comment]
Did you try it with a manually written requirements.txt with just the failing dependency in it?
`arize-phoenix-evals==0.17.2` is the issue it seems.
