### ISSUE TITLE
Broken on pip 20.1

### ISSUE THREAD

**Issue by craigds** [dhatim/python-license-check#40]
With pip 20.1 (released today) and liccheck 0.4.2, we get this:

```
$ liccheck -l CAUTIOUS -s requirements/licenses.ini -r requirements.txt
gathering licenses...
Traceback (most recent call last):
  File "/Users/cdestigter/checkout/sno/venv/bin/liccheck", line 11, in <module>
    load_entry_point('liccheck==0.4.2', 'console_scripts', 'liccheck')()
  File "/Users/cdestigter/checkout/sno/venv/lib/python3.7/site-packages/liccheck/command_line.py", line 316, in main
    sys.exit(run(args))
  File "/Users/cdestigter/checkout/sno/venv/lib/python3.7/site-packages/liccheck/command_line.py", line 311, in run
    return process(args.requirement_txt_file, strategy, args.level)
  File "/Users/cdestigter/checkout/sno/venv/lib/python3.7/site-packages/liccheck/command_line.py", line 246, in process
    pkg_info = get_packages_info(requirement_file)
  File "/Users/cdestigter/checkout/sno/venv/lib/python3.7/site-packages/liccheck/command_line.py", line 127, in get_packages_info
    if req.markers:
AttributeError: 'ParsedRequirement' object has no attribute 'markers'
```

**Comment by ochedru** [comment]
Indeed pip has been heavily refactored in version 20.1 (check out e.g. https://github.com/pypa/pip/commit/90e4eb3eedc7c550c2dd036b7a535cdec50a93d5), and liccheck depend on its internals.
