### ISSUE TITLE
VersionConflict: zipp

### ISSUE THREAD

**Issue by MartinThoma** [dhatim/python-license-check#58]
```
$ pyenv local 3.8.4
$ python -m venv venv
$ source venv/bin/activate
$ pip install liccheck
$ liccheck -s license-strategy.ini -r requirements-dev.txt
gathering licenses...
Traceback (most recent call last):
  File "/home/moose/GitHub/MartinThoma/mpu/venv/bin/liccheck", line 8, in <module>
    sys.exit(main())
  File "/home/moose/GitHub/MartinThoma/mpu/venv/lib/python3.8/site-packages/liccheck/command_line.py", line 332, in main
    sys.exit(run(args))
  File "/home/moose/GitHub/MartinThoma/mpu/venv/lib/python3.8/site-packages/liccheck/command_line.py", line 327, in run
    return process(args.requirement_txt_file, strategy, args.level, args.reporting_txt_file, args.no_deps)
  File "/home/moose/GitHub/MartinThoma/mpu/venv/lib/python3.8/site-packages/liccheck/command_line.py", line 237, in process
    pkg_info = get_packages_info(requirement_file, no_deps)
  File "/home/moose/GitHub/MartinThoma/mpu/venv/lib/python3.8/site-packages/liccheck/command_line.py", line 153, in get_packages_info
    packages = [transform(dist) for dist in resolve_func(requirements)]
  File "/home/moose/GitHub/MartinThoma/mpu/venv/lib/python3.8/site-packages/liccheck/command_line.py", line 153, in <listcomp>
    packages = [transform(dist) for dist in resolve_func(requirements)]
  File "/home/moose/GitHub/MartinThoma/mpu/venv/lib/python3.8/site-packages/liccheck/requirements.py", line 47, in resolve
    for dist in pkg_resources.working_set.resolve(requirements):
  File "/home/moose/GitHub/MartinThoma/mpu/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'zipp==3.1.0' distribution was not found and is required by the application
```

**Comment by MartinThoma** [comment]
I don't know where this came from, but it is gone.
