### ISSUE TITLE
pkg_resources.VersionConflict: (pandas 1.3.5 (~/miniconda3/envs/myenv/lib/python3.8/site-packages), Requirement.parse('pandas==1.3.3'))

### ISSUE THREAD

**Issue by asmith26** [dhatim/python-license-check#80]
Hi there,

I'm getting this `pkg_resources.VersionConflict` error. 

```python
$ liccheck -s liccheck.ini

~/miniconda3/envs/myenv/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
gathering licenses...
Traceback (most recent call last):
  File "~/miniconda3/envs/myenv/bin/liccheck", line 8, in <module>
    sys.exit(main())
  File "~/miniconda3/envs/myenv/lib/python3.8/site-packages/liccheck/command_line.py", line 336, in main
    sys.exit(run(args))
  File "~/miniconda3/envs/myenv/lib/python3.8/site-packages/liccheck/command_line.py", line 331, in run
    return process(args.requirement_txt_file, strategy, args.level, args.reporting_txt_file, args.no_deps)
  File "~/miniconda3/envs/myenv/lib/python3.8/site-packages/liccheck/command_line.py", line 241, in process
    pkg_info = get_packages_info(requirement_file, no_deps)
  File "~/miniconda3/envs/myenv/lib/python3.8/site-packages/liccheck/command_line.py", line 157, in get_packages_info
    packages = [transform(dist) for dist in resolve_func(requirements)]
  File "~/miniconda3/envs/myenv/lib/python3.8/site-packages/liccheck/command_line.py", line 157, in <listcomp>
    packages = [transform(dist) for dist in resolve_func(requirements)]
  File "~/miniconda3/envs/myenv/lib/python3.8/site-packages/liccheck/requirements.py", line 51, in resolve
    for dist in pkg_resources.working_set.resolve(requirements):
  File "~/miniconda3/envs/myenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 782, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pandas 1.3.5 (~/miniconda3/envs/myenv/lib/python3.8/site-packages), Requirement.parse('pandas==1.3.3'))
```

I'll admit I don't fully understand the error. I'm also a bit confused as I didn't think `liccheck` would check for dependency version conflicts - is there a way to turn this off maybe?

Many thanks for any help, and for this great tool!

**Comment by asmith26** [comment]
I found this was as a result of having a different version of pandas installed to what my **requirements.txt** specified.
