### ISSUE TITLE
DistributionNotFound: The 'greenlet==1.1.3' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by mdczaplicki** [dhatim/python-license-check#90]
Running `liccheck` on this `requirements.txt`
```
alembic==1.8.1 
anyio==3.6.1 
aredis==1.1.8 
certifi==2022.6.15.2 
click==8.1.3 
colorama==0.4.5 
fastapi==0.83.0 
greenlet==1.1.3
h11==0.12.0 
httpcore==0.15.0 
httpx==0.23.0 
idna==3.4 
importlib-metadata==4.2.0 
importlib-resources==5.9.0 
mako==1.2.2 
markupsafe==2.1.1 
pydantic==1.10.2 
rfc3986[idna2008]==1.5.0 
sentry-sdk==1.9.8 
sniffio==1.3.0 
sqlalchemy-utils==0.38.3 
sqlalchemy==1.4.41 
starlette==0.19.1 
typing-extensions==4.3.0 
urllib3==1.26.12 
uvicorn==0.18.3 
zipp==3.8.1 
```
raises 
```
gathering licenses...
Traceback (most recent call last):
  File "/Users/marek/Library/Caches/pypoetry/virtualenvs/big-battery-Zhirr-W2-py3.7/bin/liccheck", line 8, in <module>
    sys.exit(main())
  File "/Users/marek/Library/Caches/pypoetry/virtualenvs/big-battery-Zhirr-W2-py3.7/lib/python3.7/site-packages/liccheck/command_line.py", line 399, in main
    sys.exit(run(args))
  File "/Users/marek/Library/Caches/pypoetry/virtualenvs/big-battery-Zhirr-W2-py3.7/lib/python3.7/site-packages/liccheck/command_line.py", line 389, in run
    args['no_deps'])
  File "/Users/marek/Library/Caches/pypoetry/virtualenvs/big-battery-Zhirr-W2-py3.7/lib/python3.7/site-packages/liccheck/command_line.py", line 250, in process
    pkg_info = get_packages_info(requirement_file, no_deps)
  File "/Users/marek/Library/Caches/pypoetry/virtualenvs/big-battery-Zhirr-W2-py3.7/lib/python3.7/site-packages/liccheck/command_line.py", line 166, in get_packages_info
    packages = [transform(dist) for dist in resolve_func(requirements)]
  File "/Users/marek/Library/Caches/pypoetry/virtualenvs/big-battery-Zhirr-W2-py3.7/lib/python3.7/site-packages/liccheck/command_line.py", line 166, in <listcomp>
    packages = [transform(dist) for dist in resolve_func(requirements)]
  File "/Users/marek/Library/Caches/pypoetry/virtualenvs/big-battery-Zhirr-W2-py3.7/lib/python3.7/site-packages/liccheck/requirements.py", line 51, in resolve
    for dist in pkg_resources.working_set.resolve(requirements):
  File "/Users/marek/Library/Caches/pypoetry/virtualenvs/big-battery-Zhirr-W2-py3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'greenlet==1.1.3' distribution was not found and is required by the application
```

Same goes for `colorama==0.4.5 `

**Comment by Merinorus** [comment]
Hi,
Same with `selenium==4.4.3` or just `selenium` here.

**Comment by Sahith-8055** [comment]
Hi,
Same here with `wrapt==1.15.0`.

gathering licenses...
Traceback (most recent call last):
  File "/usr/local/bin/liccheck", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/liccheck/command_line.py", line 517, in main
    sys.exit(run(args))
             ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/liccheck/command_line.py", line 497, in run
    return process(
           ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/liccheck/command_line.py", line 313, in process
    pkg_info = get_packages_info(requirement_file, no_deps)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/liccheck/command_line.py", line 198, in get_packages_info
    packages = [transform(dist) for dist in resolve_func(requirements)]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/liccheck/command_line.py", line 198, in <listcomp>
    packages = [transform(dist) for dist in resolve_func(requirements)]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/liccheck/requirements.py", line 51, in resolve
    for dist in pkg_resources.working_set.resolve(requirements):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt==1.15.0' distribution was not found and is required by the application

**Comment by omercnet** [comment]
this happens when liccheck does not run in the same venv as the installed packages
